//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEXSTER.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DEXSTER.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adb {
            get {
                object obj = ResourceManager.GetObject("adb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AdbWinApi {
            get {
                object obj = ResourceManager.GetObject("AdbWinApi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bunifu_UI_v1_52 {
            get {
                object obj = ResourceManager.GetObject("Bunifu_UI_v1_52", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DEXGUESTV1 {
            get {
                object obj = ResourceManager.GetObject("DEXGUESTV1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Guna_UI2 {
            get {
                object obj = ResourceManager.GetObject("Guna_UI2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;产品类型，对于一些产品需要进行不同的定制
        ///[Product]
        ///KeyName = MobileGamePC
        ///VMIndexBase = 0
        ///
        ///;产品UI定制
        ///[UI]
        ///Title = DEXSTERLOOP_High_Ver
        ///GiftVisible = 1
        ///AccountSwitchVisible = 0
        ///VtStatusVisible = 1
        ///ToolbarFoldStatus = 0
        ///LogoVisible = 1
        ///
        ///;引擎配置
        ///[Engine]
        ///VMWidth = 0
        ///VMHeight = 0
        ///VMDPI = 0
        ///Renderer = 0
        ///Aow = 1
        ///MigrateApk = 1
        ///
        ///;引擎配置
        ///[Engine_100038]
        ///VMWidth = 720
        ///VMHeight = 1280
        ///VMDPI = 320
        ///Renderer = 0
        ///Aow = 1
        ///MigrateApk = 1
        ///
        ///;新剑侠情缘
        ///[UI_50]
        ///Title = 《新剑侠情缘》电脑版
        ///PassthroughInput = 1
        ///
        ///;传奇霸业
        ///[UI_138]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string High_Ver {
            get {
                return ResourceManager.GetString("High_Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;产品类型，对于一些产品需要进行不同的定制
        ///[Product]
        ///KeyName = MobileGamePC
        ///VMIndexBase = 0
        ///
        ///;产品UI定制
        ///[UI]
        ///Title = DEXSTERLOOP_Low_Ver
        ///GiftVisible = 1
        ///AccountSwitchVisible = 0
        ///VtStatusVisible = 1
        ///ToolbarFoldStatus = 0
        ///LogoVisible = 1
        ///
        ///;引擎配置
        ///[Engine]
        ///VMWidth = 0
        ///VMHeight = 0
        ///VMDPI = 0
        ///Renderer = 0
        ///Aow = 1
        ///MigrateApk = 1
        ///
        ///;引擎配置
        ///[Engine_100038]
        ///VMWidth = 720
        ///VMHeight = 1280
        ///VMDPI = 320
        ///Renderer = 0
        ///Aow = 1
        ///MigrateApk = 1
        ///
        ///;新剑侠情缘
        ///[UI_50]
        ///Title = 《新剑侠情缘》电脑版
        ///PassthroughInput = 1
        ///
        ///;传奇霸业
        ///[UI_138]
        ///T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Low_Ver {
            get {
                return ResourceManager.GetString("Low_Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;产品类型，对于一些产品需要进行不同的定制
        ///[Product]
        ///KeyName = MobileGamePC
        ///VMIndexBase = 0
        ///
        ///;产品UI定制
        ///[UI]
        ///Title = DEXSTERLOOP_Risk_Ver
        ///GiftVisible = 1
        ///AccountSwitchVisible = 0
        ///VtStatusVisible = 1
        ///ToolbarFoldStatus = 0
        ///LogoVisible = 1
        ///
        ///;引擎配置
        ///[Engine]
        ///VMWidth = 0
        ///VMHeight = 0
        ///VMDPI = 0
        ///Renderer = 0
        ///Aow = 1
        ///MigrateApk = 1
        ///
        ///;引擎配置
        ///[Engine_100038]
        ///VMWidth = 720
        ///VMHeight = 1280
        ///VMDPI = 320
        ///Renderer = 0
        ///Aow = 1
        ///MigrateApk = 1
        ///
        ///;新剑侠情缘
        ///[UI_50]
        ///Title = 《新剑侠情缘》电脑版
        ///PassthroughInput = 1
        ///
        ///;传奇霸业
        ///[UI_138]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Normal_Ver {
            get {
                return ResourceManager.GetString("Normal_Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Siticone_UI {
            get {
                object obj = ResourceManager.GetObject("Siticone_UI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;产品类型，对于一些产品需要进行不同的定制
        ///[Product]
        ///KeyName = MobileGamePC
        ///VMIndexBase = 0
        ///
        ///;产品UI定制
        ///[UI]
        ///Title = DEXSTERLOOP_Smart_Ver
        ///GiftVisible = 1
        ///AccountSwitchVisible = 0
        ///VtStatusVisible = 1
        ///ToolbarFoldStatus = 0
        ///LogoVisible = 1
        ///
        ///;引擎配置
        ///[Engine]
        ///VMWidth = 0
        ///VMHeight = 0
        ///VMDPI = 0
        ///Renderer = 0
        ///Aow = 1
        ///MigrateApk = 1
        ///
        ///;引擎配置
        ///[Engine_100038]
        ///VMWidth = 720
        ///VMHeight = 1280
        ///VMDPI = 320
        ///Renderer = 0
        ///Aow = 1
        ///MigrateApk = 1
        ///
        ///;新剑侠情缘
        ///[UI_50]
        ///Title = 《新剑侠情缘》电脑版
        ///PassthroughInput = 1
        ///
        ///;传奇霸业
        ///[UI_138]        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Smart_Ver {
            get {
                return ResourceManager.GetString("Smart_Ver", resourceCulture);
            }
        }
    }
}
